name: tf-env

# The version numbers have been chosen, such that it can be installed also on older hardware such as Intel Macs.
# If you have problems, try by removing all version numbers.

channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - matplotlib
  - tensorflow=2.11.0
  - biopython=1.84
  - scikit-learn=1.3.0
  - pip
  - pip:
      - ete4
